<h3>Bank note Authentication</h3>
<p>Data were extracted from images that were taken from genuine and forged banknote-like specimens. For digitization, an industrial camera usually used for print inspection was used.The final images have 400x 400 pixels. Due to the object lens and distance to the investigated object gray-scale pictures with a resolution of about 660 dpi were gained. Wavelet Transform tool were used to extract features from images. The attributes are extracted attributes of each image.</p>

In [17]:
import pandas as pd
import numpy as np

In [18]:
df=pd.read_csv("dataset.csv")

In [19]:
df.head()

   variance  skewness  curtosis  entropy  class
0   3.62160    8.6661   -2.8073 -0.44699      0
1   4.54590    8.1674   -2.4586 -1.46210      0
2   3.86600   -2.6383    1.9242  0.10645      0
3   3.45660    9.5228   -4.0112 -3.59440      0
4   0.32924   -4.4552    4.5718 -0.98880      0

In [20]:
##Dependent and Independent Features division (as always)
X=df.iloc[:,:-1]  ## X contains all the values on the each of the rows but not the last column
y=df.iloc[:,-1]   ##all rows  and all columns except last

In [21]:
X.head()

   variance  skewness  curtosis  entropy
0   3.62160    8.6661   -2.8073 -0.44699
1   4.54590    8.1674   -2.4586 -1.46210
2   3.86600   -2.6383    1.9242  0.10645
3   3.45660    9.5228   -4.0112 -3.59440
4   0.32924   -4.4552    4.5718 -0.98880

In [22]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: class, dtype: int64

In [23]:
##Test train split
from sklearn.model_selection import train_test_split

In [24]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=0)

In [25]:
##implimenting random forest classifier
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier()
classifier.fit(X_train,y_train)

RandomForestClassifier()

In [26]:
## prediction
y_pred=classifier.predict(X_test)

In [27]:
##check accuracy
from sklearn.metrics import accuracy_score
score = accuracy_score(y_test,y_pred)

In [28]:
score

0.9902912621359223

In [32]:
##create a pickle file using serialization
import pickle as pkl
pkl_out = open("classifier.pkl","wb")  ##creationb of pickle file
pkl.dump(classifier,pkl_out)  ## very important to dump 
pkl_out.close()



##The pickle.dump function is used in Python to serialize Python objects into a byte stream, 
##allowing for the storage or transmission of these objects

In [30]:
import numpy as np

In [31]:
classifier.predict([[2,3,4,1]])

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

array([0], dtype=int64)